name: Check code quality

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: Run linting and formatting
      run: |
        # The arguments used here should coincide with those in .vscode/settings.json
        black . --check
        isort . --check --profile=black --known-local-folder=fiberoptics
        flake8 . --per-file-ignores=__init__.py:F401 --ignore=E203,E501,W503,E712
    - name: Run tests
      run: |
        pytest ./tests --cov=./fiberoptics/common
